[package]
name        =  "fsrs"
description =  "Fullstack Rust"
version     =  "0.0.1"
authors     = ["Dmitry Ponyatov <dponyatov@gmail.com>"]
license     =  "MIT"
homepage    =  "https://github.com/ponyatov/fsrs"
edition     =  "2024"

[dependencies]
actix-web = "4.11.0"
env_logger = "0.11.8"
serde = {version="1.0.219",features = ["derive"]}
serde_json = "1.0.140"

[dev-dependencies]
[build-dependencies]
