[package]
name        =  "fsrs"
description =  "Fullstack Rust"
version     =  "0.0.1"
authors     = ["Dmitry Ponyatov <dponyatov@gmail.com>"]
license     =  "MIT"
homepage    =  "https://github.com/ponyatov/fsrs"
edition     =  "2024"

[dependencies]
actix = "0.13.5"
hyper = "1.6.0"

[dev-dependencies]
[build-dependencies]
