[source.crates-io]
replace-with = 'ustc'

[source.ustc]
registry = "sparse+https://mirrors.ustc.edu.cn/crates.io-index/"
[source.tsinghua]
registry = "sparse+https://mirrors.tuna.tsinghua.edu.cn/crates.io-index/"

[build]
target = "x86_64-unknown-linux-gnu"

[target.x86_64-unknown-linux-gnu]
linker = "x86_64-linux-gnu-gcc"

[target.aarch64-unknown-linux-gnu]
linker = "aarch64-linux-gnu-gcc"

[target.thumbv7m-none-eabi]
linker = "arm-none-eabi-gcc"
runner = [
    'qemu-system-arm',
    '-machine','netduino2','-cpu','cortex-m3',
    '-nographic','-semihosting-config','enable=on,target=native',
    '-kernel'
]
rustflags = [
    "-C", "link-arg=-Tlink.x",
    "-C", "link-arg=-nostartfiles",
]

[target.thumbv7em-none-eabihf]
linker = "arm-none-eabi-gcc"
runner = [
    'qemu-system-arm',
    '-machine','netduinoplus2','-cpu','cortex-m4',
    '-nographic','-semihosting-config','enable=on,target=native',
    '-kernel'
]
rustflags = [
    "-C", "link-arg=-Tlink.x",
    "-C", "link-arg=-nostartfiles",
]

[target.wasm32-unknown-unknown]
linker = "rust-lld"

[target.i686-pc-windows-gnu]
linker = "i686-w64-mingw32-gcc"
